{"uuid": "f27487a2-f022-46e2-979d-277febd0038e", "children": ["9fe185c6-4984-497b-a485-c24254dbef52"], "befores": [{"name": "init_desktop", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\n<head>\n   <title>Status page</title>\n</head>\n<body style=\"font-family: sans-serif;\">\n<p style=\"font-size: 1.2em;font-weight: bold;margin: 1em 0px;\">Not Found</p>\n<p>The server has not found anything matching the request URI</p>\n<p>You can get technical details <a href=\"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5\">here</a>.<br>\nPlease continue your visit at our <a href=\"/\">home page</a>.\n</p>\n</body>\n</html>\n\n\n", "trace": "  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\HackathonPython\\test\\conftest.py\", line 78, in init_desktop\n    driver = webdriver.Remote(CommonOps.get_data(\"desktopServer\"), desired_caps)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\mmich\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 208, in check_response\n    raise exception_class(value)\n"}, "steps": [{"name": "Getting data from the configuration file", "status": "passed", "parameters": [{"name": "node_name", "value": "'app'"}], "start": 1640712019958, "stop": 1640712019960}, {"name": "Getting data from the configuration file", "status": "passed", "parameters": [{"name": "node_name", "value": "'platformName'"}], "start": 1640712019960, "stop": 1640712019960}, {"name": "Getting data from the configuration file", "status": "passed", "parameters": [{"name": "node_name", "value": "'deviceName'"}], "start": 1640712019960, "stop": 1640712019960}, {"name": "Getting data from the configuration file", "status": "passed", "parameters": [{"name": "node_name", "value": "'desktopServer'"}], "start": 1640712019960, "stop": 1640712019961}], "start": 1640712019958, "stop": 1640712020008}], "start": 1640712019958, "stop": 1640712020395}